/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fitstab.view;
import conexao.ClassConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;;

/**
 *
 * @author micha
 */
public class TelaPesquiFuncionario extends javax.swing.JInternalFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
public void consultar() {
        String sql = "SELECT * FROM tbfuncionario where idFuncionarioB =?";
        try {

            pst = con.prepareStatement(sql);
            pst.setString(1, txtFuncionarioID.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtNomePesquisaFuncionario.setText(rs.getString(2));
                txtCpfPesquisaFuncionario.setText(rs.getString(3));
                txtRGPesquisaFuncionario.setText(rs.getString(4));
                comboEstadoCivilPesquisaFuncionario.setSelectedItem(rs.getString(5));
                comboPesquisaSexoFuncionario.setSelectedItem(rs.getString(6));
                txtDataNascPesquisaFuncionario.setText(rs.getString(7));
                txtCelularPesquisaFuncionario.setText(rs.getString(8));
                txtEmailPesquisaFuncionario.setText(rs.getString(9));
                txtRuaPesquisaFuncionario.setText(rs.getString(10));
                txtBairroPesquisaFuncionario.setText(rs.getString(11));
                txtCidadePesquisaFuncionario.setText(rs.getString(12));
                txtEstadoPesquisaFuncionario.setText(rs.getString(13));
                txtCepPesquisaFuncionario.setText(rs.getString(14));
                txtEspecialidadePesquisaFuncionario.setText(rs.getString(15));

                pst.close();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
public void deletar() {
        String Sql = "DELETE FROM tbfuncionario where idFuncionarioB = ?";

        try {
            pst = con.prepareStatement(Sql);
            pst.setString(1, txtFuncionarioID.getText());
              JOptionPane.showMessageDialog(null, "Cadastro exluido");
            pst.executeUpdate();
            pst.close();
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível a exclusão" + e);
        }

    }
    public TelaPesquiFuncionario() {
        initComponents();
        con = ClassConexao.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCelularPesquisaFuncionario = new javax.swing.JTextField();
        comboPesquisaSexoFuncionario = new javax.swing.JComboBox<>();
        comboEstadoCivilPesquisaFuncionario = new javax.swing.JComboBox<>();
        txtCepPesquisaFuncionario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFuncionarioID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBairroPesquisaFuncionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRuaPesquisaFuncionario = new javax.swing.JTextField();
        txtCidadePesquisaFuncionario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEstadoPesquisaFuncionario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNomePesquisaFuncionario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEmailPesquisaFuncionario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCpfPesquisaFuncionario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPesquisaFuncionario = new javax.swing.JButton();
        txtRGPesquisaFuncionario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDataNascPesquisaFuncionario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEspecialidadePesquisaFuncionario = new javax.swing.JTextField();
        bntDeletarFuncionario = new javax.swing.JButton();

        txtCelularPesquisaFuncionario.setEditable(false);

        comboPesquisaSexoFuncionario.setEditable(true);
        comboPesquisaSexoFuncionario.setEnabled(false);

        comboEstadoCivilPesquisaFuncionario.setEditable(true);
        comboEstadoCivilPesquisaFuncionario.setEnabled(false);

        txtCepPesquisaFuncionario.setEditable(false);

        jLabel1.setText("CPF");
        jLabel1.setEnabled(false);

        jLabel14.setText("Digite o ID");

        jLabel2.setText("RG");
        jLabel2.setEnabled(false);

        jLabel3.setText("Estado Cilvil");
        jLabel3.setEnabled(false);

        jLabel4.setText("Sexo");
        jLabel4.setEnabled(false);

        jLabel5.setText("Data Nascimento");
        jLabel5.setEnabled(false);

        txtBairroPesquisaFuncionario.setEditable(false);

        jLabel6.setText("Celular");
        jLabel6.setEnabled(false);

        txtRuaPesquisaFuncionario.setEditable(false);

        txtCidadePesquisaFuncionario.setEditable(false);

        jLabel7.setText("E-Mail");
        jLabel7.setEnabled(false);

        jLabel8.setText("Rua");
        jLabel8.setEnabled(false);

        txtEstadoPesquisaFuncionario.setEditable(false);

        jLabel9.setText("Bairro");
        jLabel9.setEnabled(false);

        jLabel10.setText("Cidade");
        jLabel10.setEnabled(false);

        txtNomePesquisaFuncionario.setEditable(false);

        jLabel11.setText("Estado");
        jLabel11.setEnabled(false);

        txtEmailPesquisaFuncionario.setEditable(false);

        jLabel12.setText("Cep");
        jLabel12.setEnabled(false);

        txtCpfPesquisaFuncionario.setEditable(false);

        jLabel13.setText("Nome");
        jLabel13.setEnabled(false);

        txtPesquisaFuncionario.setText("Pesquisar");
        txtPesquisaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaFuncionarioActionPerformed(evt);
            }
        });

        txtRGPesquisaFuncionario.setEditable(false);

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel15.setText("Tela Pesquisa Funcionario e Deletar");

        txtDataNascPesquisaFuncionario.setEditable(false);

        jLabel16.setText("Especialidade");
        jLabel16.setEnabled(false);

        txtEspecialidadePesquisaFuncionario.setEditable(false);

        bntDeletarFuncionario.setText("Deletar Funcionario");
        bntDeletarFuncionario.setEnabled(false);
        bntDeletarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDeletarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFuncionarioID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtPesquisaFuncionario)
                        .addGap(95, 95, 95)
                        .addComponent(bntDeletarFuncionario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(67, 67, 67)
                                .addComponent(txtNomePesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(79, 79, 79)
                                .addComponent(txtCpfPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(85, 85, 85)
                                .addComponent(txtRGPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(36, 36, 36)
                                .addComponent(comboEstadoCivilPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(63, 63, 63)
                                .addComponent(txtCelularPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(66, 66, 66)
                                .addComponent(txtEmailPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(75, 75, 75)
                                        .addComponent(comboPesquisaSexoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(9, 9, 9)
                                        .addComponent(txtDataNascPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel12))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtRuaPesquisaFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                            .addComponent(txtBairroPesquisaFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                            .addComponent(txtCidadePesquisaFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                            .addComponent(txtEstadoPesquisaFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                            .addComponent(txtCepPesquisaFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEspecialidadePesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(7, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtFuncionarioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisaFuncionario)
                    .addComponent(bntDeletarFuncionario))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtNomePesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtRuaPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtCpfPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtBairroPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtRGPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtCidadePesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtEstadoPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(comboEstadoCivilPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtCepPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(comboPesquisaSexoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtDataNascPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtEspecialidadePesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtCelularPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addComponent(txtEmailPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaFuncionarioActionPerformed
        consultar();
        bntDeletarFuncionario.setEnabled(true);
    }//GEN-LAST:event_txtPesquisaFuncionarioActionPerformed

    private void bntDeletarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDeletarFuncionarioActionPerformed
        deletar();
    }//GEN-LAST:event_bntDeletarFuncionarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntDeletarFuncionario;
    private javax.swing.JComboBox<String> comboEstadoCivilPesquisaFuncionario;
    private javax.swing.JComboBox<String> comboPesquisaSexoFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBairroPesquisaFuncionario;
    private javax.swing.JTextField txtCelularPesquisaFuncionario;
    private javax.swing.JTextField txtCepPesquisaFuncionario;
    private javax.swing.JTextField txtCidadePesquisaFuncionario;
    private javax.swing.JTextField txtCpfPesquisaFuncionario;
    private javax.swing.JTextField txtDataNascPesquisaFuncionario;
    private javax.swing.JTextField txtEmailPesquisaFuncionario;
    private javax.swing.JTextField txtEspecialidadePesquisaFuncionario;
    private javax.swing.JTextField txtEstadoPesquisaFuncionario;
    private javax.swing.JTextField txtFuncionarioID;
    private javax.swing.JTextField txtNomePesquisaFuncionario;
    private javax.swing.JButton txtPesquisaFuncionario;
    private javax.swing.JTextField txtRGPesquisaFuncionario;
    private javax.swing.JTextField txtRuaPesquisaFuncionario;
    // End of variables declaration//GEN-END:variables
}
