/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fitstab.view;

/**
 *
 * @author micha
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        Panel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuCadCliente = new javax.swing.JMenuItem();
        menuPesquisaCliente = new javax.swing.JMenuItem();
        menuAtualizarCliente = new javax.swing.JMenuItem();
        menuCadFuncionario = new javax.swing.JMenuItem();
        menuPesquisaFuncionario = new javax.swing.JMenuItem();
        menuAtualizarFuncionario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setBackground(new java.awt.Color(62, 67, 76));
        Panel1.setToolTipText("");
        Panel1.setName("Tela"); // NOI18N

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        jMenu2.setText("Cadastro");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCadCliente.setText("Cadastro Cliente");
        menuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadClienteActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadCliente);

        menuPesquisaCliente.setText("Pesquisa Cliente");
        menuPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisaClienteActionPerformed(evt);
            }
        });
        jMenu2.add(menuPesquisaCliente);

        menuAtualizarCliente.setText("Atualizar Cliente");
        menuAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAtualizarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(menuAtualizarCliente);

        menuCadFuncionario.setText("Cadastrar Funcionario");
        menuCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFuncionarioActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadFuncionario);

        menuPesquisaFuncionario.setText("Pesquisa Funcionario");
        menuPesquisaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisaFuncionarioActionPerformed(evt);
            }
        });
        jMenu2.add(menuPesquisaFuncionario);

        menuAtualizarFuncionario.setText("Atualizar Funcionario");
        menuAtualizarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAtualizarFuncionarioActionPerformed(evt);
            }
        });
        jMenu2.add(menuAtualizarFuncionario);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1078, 705));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
TelaPesquiFuncionario tc4 = new TelaPesquiFuncionario();
    TelaCadCliente tc1 = new TelaCadCliente();
    TelaPesquiCliente tc2 = new TelaPesquiCliente();
    TelaCadFuncionario tc3 = new TelaCadFuncionario();
    TelaAtualizarFuncionario tc5 = new TelaAtualizarFuncionario();
    TelaAtualizarCliente tc6 = new TelaAtualizarCliente();
    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void menuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadClienteActionPerformed

        tc1.setVisible(true);
        Panel1.add(tc1);
        tc2.setVisible(false);
        tc3.setVisible(false);
        tc4.setVisible(false);
        tc6.setVisible(false);
        tc5.setVisible(false);
    }//GEN-LAST:event_menuCadClienteActionPerformed

    private void menuPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisaClienteActionPerformed

        tc2.setVisible(true);
        Panel1.add(tc2);
        tc1.setVisible(false);
        tc3.setVisible(false);
        tc4.setVisible(false);
        tc6.setVisible(false);
        tc5.setVisible(false);
    }//GEN-LAST:event_menuPesquisaClienteActionPerformed

    private void menuCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFuncionarioActionPerformed

        tc3.setVisible(true);
        Panel1.add(tc3);
        tc2.setVisible(false);
        tc1.setVisible(false);
        tc4.setVisible(false);
        tc6.setVisible(false);
        tc5.setVisible(false);
    }//GEN-LAST:event_menuCadFuncionarioActionPerformed

    private void menuPesquisaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisaFuncionarioActionPerformed

        tc4.setVisible(true);
        Panel1.add(tc4);
        tc2.setVisible(false);
        tc3.setVisible(false);
        tc1.setVisible(false);
        tc6.setVisible(false);
        tc5.setVisible(false);

    }//GEN-LAST:event_menuPesquisaFuncionarioActionPerformed

    private void menuAtualizarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAtualizarFuncionarioActionPerformed
        tc5.setVisible(true);
        Panel1.add(tc5);
        tc2.setVisible(false);
        tc1.setVisible(false);
        tc4.setVisible(false);
        tc3.setVisible(false);
        tc6.setVisible(false);
    }//GEN-LAST:event_menuAtualizarFuncionarioActionPerformed

    private void menuAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAtualizarClienteActionPerformed
        tc6.setVisible(true);
        Panel1.add(tc6);
        tc2.setVisible(false);
        tc1.setVisible(false);
        tc4.setVisible(false);
        tc5.setVisible(false);
        tc3.setVisible(false);
    }//GEN-LAST:event_menuAtualizarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAtualizarCliente;
    private javax.swing.JMenuItem menuAtualizarFuncionario;
    private javax.swing.JMenuItem menuCadCliente;
    private javax.swing.JMenuItem menuCadFuncionario;
    private javax.swing.JMenuItem menuPesquisaCliente;
    private javax.swing.JMenuItem menuPesquisaFuncionario;
    // End of variables declaration//GEN-END:variables
}
